// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// `FirebaseOptions` when no explicit native options are provided.
/// This file intentionally left minimal. For production, configure Firebase Console.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey123456789', // Demo key
    appId: '1:000000000:web:0000000000',
    messagingSenderId: '000000000',
    projectId: 'flutter-news-app',
    authDomain: 'flutter-news-app.firebaseapp.com',
    storageBucket: 'flutter-news-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey123456789',
    appId: '1:000000000:android:0000000000',
    messagingSenderId: '000000000',
    projectId: 'flutter-news-app',
    storageBucket: 'flutter-news-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey123456789',
    appId: '1:000000000:ios:0000000000',
    messagingSenderId: '000000000',
    projectId: 'flutter-news-app',
    storageBucket: 'flutter-news-app.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );
}
